/**
 * THE STANDING RULE, AS A CHECK: every action the UI OFFERS, the engine ACCEPTS.
 *
 * "Offer only legal targets from the view's queries, so rejections are rare because illegal
 * options are not offered" (Shantanu, 4 September 2026) is a rule about a function —
 * `offeredActions(view)` in packages/ui — and a rule about a function can be tested against
 * the oracle it is supposed to agree with. This replays recorded bot games, and at every
 * command-phase state, for every cell AND every resident, applies every offer to a clone of
 * the state through the engine. An offer the engine rejects fails the suite, naming the
 * action and the reason.
 *
 * THE PER-ACTION FLOOR (CP3, FINDINGS #54) replaces the global vacuity guard rather than
 * joining it. The corpus is generated by a bot that never moves the Neutrophil and never
 * repositions a resident, so `net` was offered ZERO times across 652 states and the harness
 * had been green over it without ever checking it — the third instrument the same generator
 * gap reached (#1 → #47 → here), with residents about to be the fourth. A global guard cannot
 * see one silent action inside thousands of offers; a floor per action can. The actions the
 * corpus cannot reach are judged on CONSTRUCTED states — found in the corpus and driven
 * through the engine to where the bot never goes (`constructed.ts`).
 *
 * Two controls: the over-offer (every invader offered to the Killer T) must produce
 * rejections, and the floor must FIRE on the corpus alone — `net` and `resengulf` at zero —
 * which is also the proof that the constructed states are what covers them.
 *
 * The test spans the ui → session → engine join the way a player's tap does; it is the kind
 * of test FINDINGS #50 asked for.
 */

import { describe, expect, it } from 'vitest';

import * as engine from '@immunity-wars/engine';
import { installRng, restoreRng } from '@immunity-wars/equivalence/rng';
import type { Engine, GameState } from '@immunity-wars/equivalence/types';
import { LocalSession, MemoryStorage, type SessionView } from '@immunity-wars/session';
import { offeredActions, type Offered } from '@immunity-wars/ui';

import { clone, commandStates, constructedStates } from './constructed.js';

const PORT = engine as unknown as Engine;
const CELLS = ['macrophage', 'neutrophil', 'bcell', 'tcell', 'helper', 'nk', 'eosinophil'];
const SEEDS = [0x51de, 0x7f2a, 0x1234];

/**
 * Every action `offered.ts` can emit. Each must be OFFERED at least once somewhere the
 * harness looks, or the harness is not known to check it. Grows with each checkpoint.
 */
const OFFERABLE = [
  'move',
  'engulf',
  'strike',
  'degranulate',
  'net',
  'snipe',
  'nkkill',
  'tag',
  'neutralise',
  'produce',
  'recall',
  'hop',
  'resmove',
  'resengulf',
  'memoryKill',
  'antivenom',
  'orderAntivenom',
  'clonalSelection',
  'vaccinate',
];

interface Verdict {
  offers: number;
  perAction: Record<string, number>;
  rejected: { action: string; actor: string; error: string }[];
}

const emptyVerdict = (): Verdict => ({ offers: 0, perAction: {}, rejected: [] });

function merge(into: Verdict, v: Verdict): void {
  into.offers += v.offers;
  for (const [a, n] of Object.entries(v.perAction))
    into.perAction[a] = (into.perAction[a] ?? 0) + n;
  into.rejected.push(...v.rejected);
}

/** Actions in `floor` offered fewer than `min` times — the floor's own verdict. */
function shortfall(perAction: Record<string, number>, floor: string[], min = 1): string[] {
  return floor.filter((a) => (perAction[a] ?? 0) < min);
}

/**
 * Apply every offer `offer(view)` makes — for every cell and every resident of `state` — to a
 * clone, through the engine.
 */
function judge(state: GameState, offer: (view: SessionView) => Offered): Verdict {
  const verdict = emptyVerdict();
  const raw = state as unknown as Record<string, unknown>;
  const pid = (raw['players'] as string[])[0] ?? '';
  const subjects: { cell: string | null; resident: string | null }[] = [
    // The BODY — nothing selected: `offeredActions` hands over to `bodyOffers` (CP4).
    { cell: null, resident: null },
    ...CELLS.map((cell) => ({ cell, resident: null })),
    ...Object.keys((raw['residents'] as Record<string, unknown> | undefined) ?? {}).map(
      (resident) => ({ cell: null, resident }),
    ),
  ];
  for (const subject of subjects) {
    const s = LocalSession.resume(clone(state), { storage: new MemoryStorage(), now: () => 0 });
    s.setSelection({ ...subject, family: null });
    const offered = offer(s.getView());
    s.dispose();
    for (const o of [...offered.board, ...offered.buttons]) {
      verdict.offers += 1;
      verdict.perAction[o.action] = (verdict.perAction[o.action] ?? 0) + 1;
      const g2 = clone(state);
      installRng(1);
      try {
        const r = PORT.applyAction(g2, { ...o.params, pid } as never) as {
          ok: boolean;
          error?: string;
        };
        if (!r.ok) {
          const actor = o.cell ?? (o.organ !== undefined ? `resident:${o.organ}` : 'body');
          verdict.rejected.push({ action: o.action, actor, error: r.error ?? '' });
        }
      } finally {
        restoreRng();
      }
    }
  }
  return verdict;
}

/** The corpus verdict, computed once — the recorded games are the slow part. */
function judgeCorpus(offer: (view: SessionView) => Offered): { verdict: Verdict; states: number } {
  const verdict = emptyVerdict();
  let states = 0;
  for (const seed of SEEDS) {
    for (const difficulty of ['training', 'normal', 'hard']) {
      for (const st of commandStates(seed, difficulty, 80)) {
        states += 1;
        const v = judge(st, offer);
        v.rejected = v.rejected.map((r) => ({ ...r, error: `${difficulty}/${seed}: ${r.error}` }));
        merge(verdict, v);
      }
    }
  }
  return { verdict, states };
}

const table = (perAction: Record<string, number>): string =>
  OFFERABLE.map((a) => `${a}=${String(perAction[a] ?? 0)}`).join(' ');

describe('offered ⊆ accepted — the standing rule as a check', () => {
  const corpus = judgeCorpus(offeredActions);
  const constructed = constructedStates();

  it('the constructed states exist — a resident meal and a NET stand were reachable (vacuity guard)', () => {
    expect(constructed.map((c) => c.label).sort()).toEqual(['net stand', 'resident meal']);
  });

  it('every offer the UI makes, the engine accepts — recorded games on every difficulty, plus the constructed states', () => {
    const all = emptyVerdict();
    merge(all, corpus.verdict);
    for (const c of constructed) {
      const v = judge(c.state, offeredActions);
      v.rejected = v.rejected.map((r) => ({ ...r, error: `${c.label}: ${r.error}` }));
      merge(all, v);
    }
    expect(corpus.states, 'no command-phase states were reached').toBeGreaterThan(50);
    const rejected = all.rejected.map((r) => `${r.actor} ${r.action} — ${r.error}`);
    expect(
      rejected,
      `the UI offered what the engine rejects:\n  ${rejected.slice(0, 12).join('\n  ')}`,
    ).toEqual([]);
    // THE FLOOR: every action the UI can emit was offered somewhere the harness looked.
    expect(
      shortfall(all.perAction, OFFERABLE),
      `actions the harness never saw offered — a green run over them proves nothing\n  ${table(all.perAction)}`,
    ).toEqual([]);
  });

  it('CONTROL: the floor FIRES on the corpus alone — net and resengulf at zero — so the constructed states are what covers them', () => {
    const missing = shortfall(corpus.verdict.perAction, OFFERABLE);
    expect(missing, `corpus-only coverage: ${table(corpus.verdict.perAction)}`).toContain('net');
    expect(missing).toContain('resengulf');
  });

  it('CONTROL: a deliberate over-offer is caught', () => {
    // The Killer T-Cell offered EVERY invader, not just snipeTargets. Some must be rejected.
    const overOffer = (view: SessionView): Offered => {
      const base = offeredActions(view);
      if (view.selection.cell !== 'tcell') return base;
      const invaders = (view.game['invaders'] as { id?: unknown }[] | undefined) ?? [];
      return {
        ...base,
        board: [
          ...base.board,
          ...invaders.map((iv) => ({
            id: `over:${String(iv.id)}`,
            kind: 'attack' as const,
            action: 'snipe',
            cell: 'tcell',
            invaderId: String(iv.id),
            label: 'over-offer',
            cost: null,
            params: { action: 'snipe', cell: 'tcell', invaderId: String(iv.id) },
          })),
        ],
      };
    };
    let rejected = 0;
    for (const st of commandStates(0x51de, 'normal', 80))
      rejected += judge(st, overOffer).rejected.length;
    expect(
      rejected,
      'the over-offer produced no rejection — this check cannot fail',
    ).toBeGreaterThan(0);
  });

  it('CONTROL (body): the memory response offered on every invader is rejected', () => {
    // memoryKill needs `remembered`; offered on every invader while nothing is selected, the
    // unremembered ones must be refused — so the body subject is known to be able to fail.
    const overOffer = (view: SessionView): Offered => {
      const base = offeredActions(view);
      if (view.selection.cell || view.selection.resident) return base;
      const invaders = (view.game['invaders'] as Record<string, unknown>[] | undefined) ?? [];
      return {
        ...base,
        board: [
          ...base.board,
          ...invaders.map((iv) => ({
            id: `over:${String(iv['id'])}`,
            kind: 'attack' as const,
            action: 'memoryKill',
            cell: null,
            invaderId: String(iv['id']),
            label: 'over-offer',
            cost: null,
            params: { action: 'memoryKill', invaderId: String(iv['id']) },
          })),
        ],
      };
    };
    let rejected = 0;
    for (const st of commandStates(0x51de, 'normal', 80))
      rejected += judge(st, overOffer).rejected.length;
    expect(
      rejected,
      'the body over-offer produced no rejection — the body subject cannot fail',
    ).toBeGreaterThan(0);
  });

  it('CONTROL (residents): a resident offered engulf where it stands at step 0 is rejected', () => {
    // FINDINGS #5 measured that nothing is ever eatable at step 0. An offer module that
    // offered resengulf on every invader in the organ would be caught by the resident loop.
    const overOffer = (view: SessionView): Offered => {
      const base = offeredActions(view);
      const organ = view.selection.resident;
      if (!organ) return base;
      const invaders = (view.game['invaders'] as Record<string, unknown>[] | undefined) ?? [];
      return {
        ...base,
        board: [
          ...base.board,
          ...invaders
            .filter((iv) => iv['organ'] === organ)
            .map((iv) => ({
              id: `over:${String(iv['id'])}`,
              kind: 'attack' as const,
              action: 'resengulf',
              cell: null,
              organ,
              invaderId: String(iv['id']),
              label: 'over-offer',
              cost: null,
              params: { action: 'resengulf', organ, invaderId: String(iv['id']) },
            })),
        ],
      };
    };
    let rejected = 0;
    for (const st of commandStates(0x51de, 'hard', 80))
      rejected += judge(st, overOffer).rejected.length;
    expect(
      rejected,
      'the resident over-offer produced no rejection — the resident loop cannot fail',
    ).toBeGreaterThan(0);
  });
});
