/**
 * THE CONTENT REACHABILITY REPORT — what the deck can actually produce, and what it cannot.
 *
 * docs/TASK_C_HANDOFF.md §3 asks for this: "emit the (type, flag) combinations the deck actually
 * contains, so a guard against an impossible combination is visible at build time rather than
 * discovered by a coverage run months later."
 *
 * It answers docs/FINDINGS.md #22 and #23, which are one problem seen from two sides:
 *
 *   #22  the ENGINE guards against states the CONTENT cannot produce
 *   #23  the CONTENT declares pathogens the ENGINE cannot produce
 *
 * Neither side's beliefs about the other were ever written down. Both were inferred. This writes
 * them down, mechanically, from the content itself.
 *
 * KNOWN-ANSWER TEST: this report must name `Diphtheria toxin` in §3 WITHOUT BEING TOLD ABOUT IT.
 * That row was found by hand at Task C planning (FINDINGS #23). If the generator misses it, the
 * generator is wrong and the rest of its output cannot be trusted — fix the generator, never the
 * report. `reachability.test.ts` asserts exactly that.
 *
 *   npx tsx tests/equivalence/reachability-report.ts          # write docs/CONTENT_REACHABILITY.md
 *   npx tsx tests/equivalence/reachability-report.ts --check  # fail if it would change
 */

import { readFileSync, writeFileSync } from 'node:fs';

import * as content from '@immunity-wars/content';

/** Every optional flag a card may carry. Derived from the deck, not from a hand-kept list. */
function flagNames(): string[] {
  const seen = new Set<string>();
  for (const c of content.DECK_MASTER) {
    for (const k of Object.keys(c)) if (k !== 'dz' && k !== 'type' && k !== 'lane') seen.add(k);
  }
  return [...seen].sort();
}

/** The (type, flag) pairs the deck actually contains. */
interface Combo {
  type: string;
  flag: string;
  cards: string[];
}

function combos(): Combo[] {
  const out = new Map<string, Combo>();
  for (const c of content.DECK_MASTER) {
    const card = c as unknown as Record<string, unknown>;
    for (const f of flagNames()) {
      if (!(f in card)) continue;
      const key = `${c.type}|${f}`;
      const hit = out.get(key) ?? { type: c.type, flag: f, cards: [] };
      hit.cards.push(c.dz);
      out.set(key, hit);
    }
  }
  return [...out.values()].sort(
    (a, b) => a.type.localeCompare(b.type) || a.flag.localeCompare(b.flag),
  );
}

/**
 * Disease names the ENGINE can mint that are not cards.
 *
 * Derived from the content wherever possible — TOXIN_MAKERS' values are emitted by an untagged
 * toxin-making bacterium — plus the names the engine constructs directly. The second group is
 * the one that cannot be derived, so it is listed here and cross-checked below: anything in
 * FAMILY that is neither a card nor accounted for here is UNREACHABLE CONTENT, which is the
 * whole point of §3.
 */
const ENGINE_MINTED: Record<string, string> = {
  'Malaria (blood)': 'a liver-stage malaria bursting (resolveSpread)',
  'Malaria (relapse)': 'the malariaRelapse rare event',
  Shingles: 'the shingles rare event',
  'Dengue (ADE)': 'the dengueADE rare event',
  'Tuberculosis (reactivated)': 'the tbReactivation rare event',
  'Pneumococcal pneumonia': 'the postFluPneumonia rare event',
};

function report(): string {
  const deck = new Set(content.DECK_MASTER.map((c) => c.dz));
  const emittedToxins = new Map(Object.entries(content.TOXIN_MAKERS).map(([b, t]) => [t, b]));

  /* --- §3: content nothing can produce --- */
  const producible = new Set<string>([
    ...deck,
    ...emittedToxins.keys(),
    ...Object.keys(ENGINE_MINTED),
  ]);
  const orphanFamily = Object.keys(content.FAMILY).filter((d) => !producible.has(d));
  const orphanTropism = Object.keys(content.TROPISM).filter((d) => !producible.has(d));

  const L: string[] = [
    '# Content reachability',
    '',
    '**Generated by `npx tsx tests/equivalence/reachability-report.ts`. Do not edit by hand.**',
    '',
    'What the content can actually produce, and what it declares but cannot. This exists because',
    '[`FINDINGS.md`](FINDINGS.md) #22 and #23 are the same problem from two sides — the engine',
    'guarding against states the content cannot produce, and the content declaring pathogens the',
    'engine cannot produce — and because neither side ever wrote its assumptions down.',
    '',
    `Deck: **${deck.size} cards**. FAMILY: **${Object.keys(content.FAMILY).length} entries**.`,
    `TROPISM: **${Object.keys(content.TROPISM).length} entries**.`,
    '',
    '---',
    '',
    '## 1. The (type, flag) combinations the deck contains',
    '',
    'A guard written for a combination absent from this table can never fire. That is not',
    'automatically wrong — the rule may be correct and merely unexercised — but it is never',
    'tested, and #13 is the proof that an untested guard can be wrong for the one card it',
    'concerns.',
    '',
    '| type | flag | cards |',
    '|---|---|---|',
  ];
  for (const c of combos()) L.push(`| \`${c.type}\` | \`${c.flag}\` | ${c.cards.join(', ')} |`);

  /* --- §2: combinations that do NOT exist --- */
  const types = [...new Set(content.DECK_MASTER.map((c) => c.type))].sort();
  const present = new Set(combos().map((c) => `${c.type}|${c.flag}`));
  L.push(
    '',
    '## 2. Flag combinations the deck does NOT contain',
    '',
    'Every `(type, flag)` pair that does not occur. An engine branch requiring one of these is',
    'unreachable with the current content.',
    '',
  );
  for (const f of flagNames()) {
    const missing = types.filter((t) => !present.has(`${t}|${f}`));
    if (missing.length)
      L.push(`- \`${f}\` never appears on: ${missing.map((m) => `\`${m}\``).join(', ')}`);
  }
  L.push(
    '',
    '**The three named in FINDINGS #22 fall out of this table.** `novel` appears only on a',
    "`virus`, so `tag`'s brand-new-antigen refusal (which accepts only bacteria/worm/parasite)",
    'can never fire — #21. `variant` appears only on a `parasite`, and `neutralise` rejects',
    'parasites, so the antigenic-variation roll can never fire — #4. `hidesInMac` likewise.',
    '',
    '## 3. Content the engine cannot produce',
    '',
    'Disease names carrying a `FAMILY` or `TROPISM` entry that nothing can ever create: not a',
    'card, not emitted by a `TOXIN_MAKERS` bacterium, not minted by a rare event.',
    '',
  );
  const orphans = [...new Set([...orphanFamily, ...orphanTropism])].sort();
  if (!orphans.length) {
    L.push('_None. Every declared disease has a producer._');
  } else {
    L.push('| disease | in FAMILY | in TROPISM |', '|---|---|---|');
    for (const d of orphans) {
      L.push(
        `| **${d}** | ${orphanFamily.includes(d) ? `\`${content.FAMILY[d]}\`` : '—'} | ` +
          `${orphanTropism.includes(d) ? 'yes' : '—'} |`,
      );
    }
    L.push(
      '',
      'See [`FINDINGS.md`](FINDINGS.md) #23. Report only — whether such a row should be deleted,',
      'or given a producer, is a design question for Kartik.',
    );
  }

  /* --- §4: cards with no FAMILY entry --- */
  const noFamily = content.DECK_MASTER.filter((c) => !(c.dz in content.FAMILY)).map((c) => c.dz);
  const noTropism = content.DECK_MASTER.filter((c) => !(c.dz in content.TROPISM)).map((c) => c.dz);
  const unexempted = noFamily.filter((d) => !content.NOVEL_ANTIGENS.has(d));
  L.push(
    '',
    '## 4. Cards missing a FAMILY or TROPISM entry',
    '',
    "A card with no `FAMILY` entry and no declared exemption would fall through `famOf`'s",
    "`?? 'EXB'` fallback and be treated as an extracellular bacterium. For a NOVEL antigen that",
    'is wrong: no existing antibody class fits a germ the body has never met, which is the',
    'entire lesson the card carries.',
    '',
    'Until Task C4 that was held only by `famOf` short-circuiting on the `novel` FLAG, so losing',
    'the flag anywhere would have silently reclassified the pathogen with every test still',
    'passing — [`FINDINGS.md`](FINDINGS.md) #13. It is now declared and schema-enforced:',
    '[`DEVIATIONS.md`](DEVIATIONS.md) #5.',
    '',
    `- no FAMILY entry: ${noFamily.length ? noFamily.map((d) => `**${d}**`).join(', ') : '_none_'}`,
    `- no TROPISM entry: ${noTropism.length ? noTropism.map((d) => `**${d}**`).join(', ') : '_none_'}`,
    '',
    'A card may have no `FAMILY` entry only if it is DECLARED in `NOVEL_ANTIGENS`, which the',
    'schema enforces — [`DEVIATIONS.md`](DEVIATIONS.md) #5. Current exemptions, and why:',
    '',
    '| exempted card | reason |',
    '|---|---|',
    ...[...content.NOVEL_ANTIGENS].map(
      (d) =>
        `| **${d}** | a novel antigen has no class by definition — that is what the card teaches |`,
    ),
    '',
    unexempted.length
      ? `⚠️ **UNDECLARED and unexempted: ${unexempted.map((d) => `**${d}**`).join(', ')}** — ` +
          `these fall through \`famOf\`'s \`?? 'EXB'\` fallback and are silently treated as ` +
          `extracellular bacteria.`
      : '_No card is missing a class without a declared reason._',
  );

  /* --- §5: the toxin emission chain, since it is the least obvious producer --- */
  L.push('', '## 5. Toxins emitted by bacteria', '', '| bacterium | emits |', '|---|---|');
  for (const [b, t] of Object.entries(content.TOXIN_MAKERS)) L.push(`| ${b} | ${t} |`);

  L.push(
    '',
    '## 6. Disease names the engine mints directly',
    '',
    '| disease | minted by |',
    '|---|---|',
  );
  for (const [d, why] of Object.entries(ENGINE_MINTED)) L.push(`| ${d} | ${why} |`);

  return L.join('\n') + '\n';
}

const OUT = 'docs/CONTENT_REACHABILITY.md';

/**
 * ONLY RUN WHEN EXECUTED DIRECTLY. NEVER ON IMPORT.
 *
 * Nothing imports this file today, so nothing is broken today. The guard is here because the
 * shape it prevents already cost this project its worst failure: at Task C5b, `i18n-extract.ts`
 * ran its generator at module top level and `i18n-engine.test.ts` imported it for a helper. ES
 * module imports evaluate BEFORE the importing module's body, so the import REGENERATED the
 * catalogue and the test then read the file it had just rewritten. Nineteen tests passed while
 * every one of five deliberate mutations was silently erased.
 *
 * **A test that regenerates its own oracle cannot fail.** The trap is invisible at the import
 * site — `import { thing } from './generator.js'` looks inert — so it is closed here rather than
 * left for whoever first wants a helper out of this file.
 */
const executedDirectly =
  process.argv[1] !== undefined && /reachability-report\.[tj]s$/.test(process.argv[1]);

if (executedDirectly) {
  const text = report();
  if (process.argv.includes('--check')) {
    const existing = readFileSync(OUT, 'utf8');
    if (existing !== text) {
      console.error(`${OUT} is out of date — re-run reachability-report.ts`);
      process.exit(1);
    }
    console.log(`${OUT} is up to date`);
  } else {
    writeFileSync(OUT, text);
    console.log(`wrote ${OUT}`);
  }
}
