/**
 * THE COVERAGE DOCUMENTS' POSITIONS, CHECKED WITHOUT RUNNING COVERAGE.
 *
 *   pnpm coverage:positions
 *
 * ============================================================================================
 * WHY THIS EXISTS: A CLASS OF CI FAILURE THAT `pnpm verify` CANNOT PREDICT
 * ============================================================================================
 *
 * `docs/COVERAGE_EXCLUSIONS.md` and `docs/COVERAGE_DEFERRED.md` are GENERATED by
 * `pnpm coverage:gate`, and CI regenerates them and requires the committed copies to match.
 * Every entry in them records a POSITION — a file and a line number — beside the source text
 * that was at that position when they were written.
 *
 * A line number is not a property of the arm. It is a property of everything ABOVE the arm. So
 * any edit that inserts or removes a line in `packages/engine/src` or `packages/content/src`
 * moves the recorded positions of every arm below it, and the committed documents go stale
 * without a single thing about coverage having changed.
 *
 * `pnpm verify` does not run coverage — deliberately, because coverage is slow. So this class
 * of staleness is INVISIBLE LOCALLY and reds the branch on CI instead. That is exactly what
 * happened on PR #70: adding the `WHY` and `DERIVED` schemas to the content pack pushed four
 * arms down `schema.ts`, the gate itself PASSED, and the drift check failed on four numbers.
 * Verify had been green.
 *
 * ============================================================================================
 * WHAT IT CHECKS, AND WHY IT COSTS NOTHING
 * ============================================================================================
 *
 * The documents already quote the source line beside every position. So the check is a
 * comparison the documents make possible themselves: read the file, take the recorded line,
 * and require the source there to still be the text recorded beside it. No coverage run, no
 * instrumentation, no `coverage/` directory. Milliseconds.
 *
 * It is a NECESSARY condition for the generated documents being current, not a sufficient one.
 * It cannot see an arm that became covered, an exclusion that went stale in meaning, or a new
 * arm that should have been listed — those need the real gate, and CI runs it. What it catches
 * is the one failure mode that is both common and completely mechanical.
 *
 * ============================================================================================
 * WHAT WOULD MAKE THIS CHECK BLIND, AND WHAT IS DONE ABOUT EACH
 * ============================================================================================
 *
 * 1. PARSING NOTHING. A regex that silently matches no entries passes trivially. So the counts
 *    are asserted against a floor and PRINTED per document and per file: read what it covered,
 *    not the verdict.
 * 2. AN EMPTY RECORDED TEXT would match any line at all, since every string starts with the
 *    empty string. Asserted against, rather than assumed absent.
 * 3. A FILE NAME THAT CANNOT BE RESOLVED, or that resolves to two files, is a FAILURE and never
 *    a skip. `queries.ts`, `effects.ts` and `schema.ts` each exist twice in this repository; a
 *    skipped entry shrinks the checked set invisibly, which is the shape of every blind check
 *    this project has found.
 * 4. GUESSING WHERE THE INSTRUMENTED FILES ARE. The roots are not written here. They are read
 *    from `vitest.coverage.config.ts`, which is the authority on what coverage measures, so a
 *    root added there cannot leave this check quietly looking at the old set.
 */

import { readdirSync, readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, '..', '..');

const EXCLUSIONS = 'docs/COVERAGE_EXCLUSIONS.md';
const DEFERRED = 'docs/COVERAGE_DEFERRED.md';

/** Floors, so that a parser matching nothing cannot pass. Set below today's counts, not at them:
 *  a floor at the current number turns every legitimate regeneration into a failure. */
const FLOOR = { exclusions: 100, deferred: 40 };

// --------------------------------------------------------------------------------------------
// Which files coverage measures — read from the coverage config, never restated here.
// --------------------------------------------------------------------------------------------

const COVERAGE_CONFIG = 'vitest.coverage.config.ts';

/**
 * The globs are READ from the coverage config rather than restated here, so a root added there
 * cannot leave this check quietly measuring the old set.
 *
 * It is read as TEXT and not imported. Importing it would pull the config into this package's
 * typecheck program, where the vitest coverage types do not resolve — measured: `pnpm verify`
 * went red on `'all' does not exist in type 'CoverageOptions'` the first time this file imported
 * it. Text is also the weaker operation, which is the right one here: nothing in that config
 * needs to be executed to learn two directory names.
 *
 * Every failure to parse is LOUD. There is no fallback set of roots, because a fallback is how
 * a check ends up confidently measuring something other than what it names.
 */
const readIncludeGlobs = (): string[] => {
  const text = readFileSync(join(REPO, COVERAGE_CONFIG), 'utf8');
  const at = text.indexOf('coverage:');
  if (at === -1) {
    console.error(
      `${COVERAGE_CONFIG} has no \`coverage:\` block, so its include globs cannot be read.`,
    );
    process.exit(1);
  }
  const m = /include:\s*\[([^\]]*)\]/.exec(text.slice(at));
  if (!m) {
    console.error(`${COVERAGE_CONFIG} declares no \`include\` inside its \`coverage:\` block.`);
    process.exit(1);
  }
  const globs = [...(m[1] as string).matchAll(/['"]([^'"]+)['"]/g)].map((q) => q[1] as string);
  if (globs.length === 0) {
    console.error(`${COVERAGE_CONFIG}'s \`coverage.include\` is empty.`);
    process.exit(1);
  }
  return globs;
};

const includeGlobs = readIncludeGlobs();

/** The static directory prefix of a glob: `packages/engine/src/**\/*.ts` -> `packages/engine/src`. */
const rootOf = (glob: string): string => {
  const star = glob.indexOf('*');
  const head = star === -1 ? glob : glob.slice(0, star);
  return head.replace(/\/+$/, '');
};

const tsFilesUnder = (dir: string): string[] => {
  const out: string[] = [];
  const abs = join(REPO, dir);
  let entries;
  try {
    entries = readdirSync(abs, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const e of entries) {
    const rel = `${dir}/${e.name}`;
    if (e.isDirectory()) out.push(...tsFilesUnder(rel));
    else if (e.name.endsWith('.ts') && !e.name.endsWith('.test.ts')) out.push(rel);
  }
  return out;
};

const byName = new Map<string, string[]>();
for (const glob of includeGlobs) {
  for (const rel of tsFilesUnder(rootOf(glob))) {
    const name = rel.split('/').pop() as string;
    const list = byName.get(name);
    if (list) list.push(rel);
    else byName.set(name, [rel]);
  }
}

// --------------------------------------------------------------------------------------------
// The entries, from both documents.
// --------------------------------------------------------------------------------------------

interface Entry {
  readonly doc: string;
  readonly docLine: number;
  readonly short: string;
  readonly line: number;
  /** The source text as recorded. Truncated by the generator in two of the three shapes, so it
   *  is compared as a PREFIX of the source line rather than as an equal. */
  readonly text: string;
}

const readDoc = (rel: string): string[] => readFileSync(join(REPO, rel), 'utf8').split(/\r?\n/);

/** Rule A and rule C: a `### file.ts` heading, then `- \`LINE\` \`TEXT\`` rows under it.
 *  Rule B: a `### file.ts:LINE` heading, then a fenced block holding the full text. */
const parseExclusions = (): Entry[] => {
  const out: Entry[] = [];
  const lines = readDoc(EXCLUSIONS);
  let current: string | null = null;
  for (let i = 0; i < lines.length; i += 1) {
    const line = (lines[i] ?? '').trim();

    const ruleB = /^### ([A-Za-z0-9_.-]+\.ts):(\d+)$/.exec(line);
    if (ruleB) {
      current = null;
      // The demonstration's own text, in the fence that follows the heading.
      let j = i + 1;
      while (j < lines.length && (lines[j] ?? '').trim() !== '```') j += 1;
      const body: string[] = [];
      j += 1;
      while (j < lines.length && (lines[j] ?? '').trim() !== '```') {
        body.push(lines[j] ?? '');
        j += 1;
      }
      out.push({
        doc: EXCLUSIONS,
        docLine: i + 1,
        short: ruleB[1] as string,
        line: Number(ruleB[2]),
        text: body.join('\n').trim(),
      });
      continue;
    }

    const heading = /^### ([A-Za-z0-9_.-]+\.ts)$/.exec(line);
    if (heading) {
      current = heading[1] as string;
      continue;
    }

    const row = /^- `(\d+)` `(.*)`$/.exec(line);
    if (row && current) {
      out.push({
        doc: EXCLUSIONS,
        docLine: i + 1,
        short: current,
        line: Number(row[1]),
        text: row[2] as string,
      });
    }
  }
  return out;
};

/** `- \`file.ts:LINE\` \`TEXT\`` — the deferred list's only shape. */
const parseDeferred = (): Entry[] => {
  const out: Entry[] = [];
  const lines = readDoc(DEFERRED);
  for (let i = 0; i < lines.length; i += 1) {
    const m = /^- `([A-Za-z0-9_.-]+\.ts):(\d+)` `(.*)`$/.exec((lines[i] ?? '').trim());
    if (m) {
      out.push({
        doc: DEFERRED,
        docLine: i + 1,
        short: m[1] as string,
        line: Number(m[2]),
        text: m[3] as string,
      });
    }
  }
  return out;
};

// --------------------------------------------------------------------------------------------
// The comparison.
// --------------------------------------------------------------------------------------------

const sources = new Map<string, string[]>();
const sourceLine = (rel: string, n: number): string | null => {
  let lines = sources.get(rel);
  if (!lines) {
    lines = readFileSync(join(REPO, rel), 'utf8').split(/\r?\n/);
    sources.set(rel, lines);
  }
  if (n < 1 || n > lines.length) return null;
  return (lines[n - 1] ?? '').trim();
};

const entries = [...parseExclusions(), ...parseDeferred()];
const problems: string[] = [];
const checkedPerFile = new Map<string, number>();
let checked = 0;

for (const e of entries) {
  const where = `${e.doc}:${e.docLine}  ${e.short}:${e.line}`;

  if (e.text.trim() === '') {
    problems.push(
      `${where}\n    THE RECORDED TEXT IS EMPTY. Every string starts with the empty string, so ` +
        `this entry would match any line at all and could never fail.`,
    );
    continue;
  }

  const paths = byName.get(e.short) ?? [];
  if (paths.length === 0) {
    problems.push(
      `${where}\n    NO INSTRUMENTED FILE IS NAMED ${e.short}. Coverage measures ` +
        `${includeGlobs.join(', ')}; nothing there carries that name.`,
    );
    continue;
  }
  if (paths.length > 1) {
    problems.push(
      `${where}\n    ${e.short} IS AMBIGUOUS among instrumented files: ${paths.join(', ')}. ` +
        `The documents record base names only, so this entry cannot be resolved.`,
    );
    continue;
  }

  const rel = paths[0] as string;
  const found = sourceLine(rel, e.line);
  if (found === null) {
    problems.push(
      `${where}\n    ${rel} HAS NO LINE ${e.line} — the file is shorter than the position recorded.`,
    );
    continue;
  }
  if (!found.startsWith(e.text)) {
    problems.push(
      `${where}\n    recorded: ${JSON.stringify(e.text.slice(0, 90))}\n` +
        `    at ${rel}:${e.line}: ${JSON.stringify(found.slice(0, 90))}`,
    );
    continue;
  }

  checked += 1;
  checkedPerFile.set(rel, (checkedPerFile.get(rel) ?? 0) + 1);
}

// --------------------------------------------------------------------------------------------
// Report what was covered, then the verdict — in that order, on purpose.
// --------------------------------------------------------------------------------------------

const fromExclusions = entries.filter((e) => e.doc === EXCLUSIONS).length;
const fromDeferred = entries.filter((e) => e.doc === DEFERRED).length;

console.log('COVERAGE DOCUMENT POSITIONS — every recorded line still holds the text beside it');
console.log('='.repeat(92));
console.log(`  ${EXCLUSIONS.padEnd(32)} ${String(fromExclusions).padStart(4)} entries parsed`);
console.log(`  ${DEFERRED.padEnd(32)} ${String(fromDeferred).padStart(4)} entries parsed`);
console.log(`  ${'verified against source'.padEnd(32)} ${String(checked).padStart(4)} entries`);
console.log('');
for (const rel of [...checkedPerFile.keys()].sort()) {
  console.log(`      ${String(checkedPerFile.get(rel)).padStart(4)}  ${rel}`);
}
console.log('');

let failed = false;

if (fromExclusions < FLOOR.exclusions || fromDeferred < FLOOR.deferred) {
  console.error(
    `PARSED TOO FEW ENTRIES: ${fromExclusions} from the exclusions (floor ${FLOOR.exclusions}) ` +
      `and ${fromDeferred} from the deferred list (floor ${FLOOR.deferred}).\n` +
      'A parser that matches nothing passes trivially, so this is a failure rather than a pass. ' +
      'Either the documents changed shape, in which case this check must be taught the new one, ' +
      'or they are far shorter than they have ever been.',
  );
  failed = true;
}

if (problems.length > 0) {
  console.error(
    `${problems.length} recorded position${problems.length === 1 ? '' : 's'} no longer holds:\n`,
  );
  for (const p of problems) console.error(`  ${p}\n`);
  console.error(
    'THE GENERATED COVERAGE DOCUMENTS ARE STALE. Nothing about coverage need have changed: a ' +
      'line inserted above an arm moves every position below it.\n' +
      'Regenerate and commit the result:  pnpm coverage:all && pnpm coverage:gate\n' +
      'CI regenerates these and requires the committed copies to match, so this fails there too.',
  );
  failed = true;
}

if (failed) process.exit(1);

console.log('EVERY RECORDED POSITION STILL HOLDS');
console.log(
  'A necessary condition, not a sufficient one: this cannot see an arm that became covered or ' +
    'one that should have been listed. Only pnpm coverage:gate can.',
);
